apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    io.portainer.kubernetes.application.note: ""
  creationTimestamp: "2022-01-25T19:03:25Z"
  generation: 1
  labels:
    io.portainer.kubernetes.application.name: geoserver
    io.portainer.kubernetes.application.owner: admin
    io.portainer.kubernetes.application.stack: astpStack
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:io.portainer.kubernetes.application.note: {}
        f:labels:
          .: {}
          f:io.portainer.kubernetes.application.name: {}
          f:io.portainer.kubernetes.application.owner: {}
          f:io.portainer.kubernetes.application.stack: {}
      f:spec:
        f:podManagementPolicy: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:serviceName: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
              f:io.portainer.kubernetes.application.name: {}
          f:spec:
            f:containers:
              k:{"name":"geoserver"}:
                .: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/geoserver_data/data"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"geoserver-49319ab1-aea1-429a-b03c-f6e2ed562c85"}:
                .: {}
                f:name: {}
                f:persistentVolumeClaim:
                  .: {}
                  f:claimName: {}
        f:updateStrategy:
          f:rollingUpdate:
            .: {}
            f:partition: {}
          f:type: {}
        f:volumeClaimTemplates: {}
    manager: Mozilla
    operation: Update
    time: "2022-01-25T19:03:25Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:availableReplicas: {}
        f:collisionCount: {}
        f:currentReplicas: {}
        f:currentRevision: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updateRevision: {}
        f:updatedReplicas: {}
    manager: kubelite
    operation: Update
    subresource: status
    time: "2022-01-29T10:31:42Z"
  name: geoserver
  namespace: arqsis
  resourceVersion: "112558"
  selfLink: /apis/apps/v1/namespaces/arqsis/statefulsets/geoserver
  uid: 1b2399ab-70a3-4ad1-95d8-f6b10cf69700
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: geoserver
  serviceName: headless-geoserver
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: geoserver
        io.portainer.kubernetes.application.name: geoserver
    spec:
      containers:
      - image: brunotslima/geoserver:latest
        imagePullPolicy: Always
        name: geoserver
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /geoserver_data/data
          name: geoserver-49319ab1-aea1-429a-b03c-f6e2ed562c85
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: geoserver-49319ab1-aea1-429a-b03c-f6e2ed562c85
        persistentVolumeClaim:
          claimName: geoserver-49319ab1-aea1-429a-b03c-f6e2ed562c85
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        app: geoserver
        io.portainer.kubernetes.application.name: geoserver
        io.portainer.kubernetes.application.owner: admin
      name: geoserver-49319ab1-aea1-429a-b03c-f6e2ed562c85
      namespace: arqsis
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 300M
      storageClassName: microk8s-hostpath
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  availableReplicas: 1
  collisionCount: 0
  currentReplicas: 1
  currentRevision: geoserver-7558b5c58b
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: geoserver-7558b5c58b
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-01-25T19:03:25Z"
  labels:
    io.portainer.kubernetes.application.name: geoserver
    io.portainer.kubernetes.application.owner: admin
    io.portainer.kubernetes.application.stack: astpStack
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:io.portainer.kubernetes.application.name: {}
          f:io.portainer.kubernetes.application.owner: {}
          f:io.portainer.kubernetes.application.stack: {}
      f:spec:
        f:clusterIP: {}
        f:internalTrafficPolicy: {}
        f:selector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: Mozilla
    operation: Update
    time: "2022-01-25T19:03:25Z"
  name: headless-geoserver
  namespace: arqsis
  resourceVersion: "32442"
  selfLink: /api/v1/namespaces/arqsis/services/headless-geoserver
  uid: 8be69574-144f-414f-bce6-a268a23712e3
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    app: geoserver
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-01-25T19:03:25Z"
  labels:
    io.portainer.kubernetes.application.name: geoserver
    io.portainer.kubernetes.application.owner: admin
    io.portainer.kubernetes.application.stack: astpStack
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:io.portainer.kubernetes.application.name: {}
          f:io.portainer.kubernetes.application.owner: {}
          f:io.portainer.kubernetes.application.stack: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:internalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:nodePort: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
          k:{"port":8080,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:nodePort: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: Mozilla
    operation: Update
    time: "2022-01-25T19:03:25Z"
  name: geoserver
  namespace: arqsis
  resourceVersion: "32441"
  selfLink: /api/v1/namespaces/arqsis/services/geoserver
  uid: 8f87f166-c6b1-4580-88ee-4f26d0786831
spec:
  clusterIP: 10.152.183.31
  clusterIPs:
  - 10.152.183.31
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: geoserver-8080-tcp
    nodePort: 30280
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: geoserver-80-tcp
    nodePort: 30281
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: geoserver
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
