apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    io.portainer.kubernetes.application.note: ""
  creationTimestamp: "2022-01-25T21:34:45Z"
  generation: 1
  labels:
    io.portainer.kubernetes.application.name: routeprice
    io.portainer.kubernetes.application.owner: admin
    io.portainer.kubernetes.application.stack: astpStack
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:io.portainer.kubernetes.application.note: {}
        f:labels:
          .: {}
          f:io.portainer.kubernetes.application.name: {}
          f:io.portainer.kubernetes.application.owner: {}
          f:io.portainer.kubernetes.application.stack: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
              f:io.portainer.kubernetes.application.name: {}
          f:spec:
            f:containers:
              k:{"name":"routeprice"}:
                .: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: Mozilla
    operation: Update
    time: "2022-01-25T21:34:45Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kubelite
    operation: Update
    subresource: status
    time: "2022-01-29T10:32:09Z"
  name: routeprice
  namespace: arqsis
  resourceVersion: "112717"
  selfLink: /apis/apps/v1/namespaces/arqsis/deployments/routeprice
  uid: cba788e7-1b95-4b05-86fe-7b7aaa781f2d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: routeprice
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: routeprice
        io.portainer.kubernetes.application.name: routeprice
    spec:
      containers:
      - image: pcerqueira25/routeprice:portainer
        imagePullPolicy: IfNotPresent
        name: routeprice
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-01-25T21:34:46Z"
    lastUpdateTime: "2022-01-25T21:34:46Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-01-25T21:34:45Z"
    lastUpdateTime: "2022-01-25T21:35:15Z"
    message: ReplicaSet "routeprice-894d6c9c8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-01-25T21:34:45Z"
  labels:
    io.portainer.kubernetes.application.name: routeprice
    io.portainer.kubernetes.application.owner: admin
    io.portainer.kubernetes.application.stack: astpStack
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:io.portainer.kubernetes.application.name: {}
          f:io.portainer.kubernetes.application.owner: {}
          f:io.portainer.kubernetes.application.stack: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:internalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":30045,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:nodePort: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: Mozilla
    operation: Update
    time: "2022-01-25T22:12:19Z"
  name: routeprice
  namespace: arqsis
  resourceVersion: "47791"
  selfLink: /api/v1/namespaces/arqsis/services/routeprice
  uid: f81ae94c-15cc-4435-bcbc-5f2296e5e61e
spec:
  clusterIP: 10.152.183.132
  clusterIPs:
  - 10.152.183.132
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: routeprice-30045-tcp
    nodePort: 30045
    port: 30045
    protocol: TCP
    targetPort: 30045
  selector:
    app: routeprice
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
